### ISSUE TITLE
Pass backup policy parameters as volume labels

### ISSUE THREAD

**Issue by raphink** [camptocamp/conplicity#1]
Each container should be able to expose backup policy parameters are labels, in the form `io.conplicity.<volume>.param`.

Examples:
- io.conplicity.pgdata.driver: postgresql
- io.conplicity.pgdata.retention: 7d

**Comment by raphink** [comment]
Two labels were added in 0.5.0:

- `io.conplicity.ignore=true` ignores the volume
- `io.conplicity.full_if_older_than=<value>` sets the time period after which a full backup is performed. Defaults to the `FULL_IF_OLDER_THAN` environment variable value

**Comment by mcanevet** [comment]
@raphink I think we can close this one

**Comment by mcanevet** [comment]
Conplicity support volume labels, but unfortunately Docker Engine does not support volume labels update yet: https://github.com/moby/moby/issues/25291
