### ISSUE TITLE
what is the purpose of putting  .conplicity.overrides file at the root of the volume

### ISSUE THREAD

**Issue by ict4ngo** [camptocamp/conplicity#111]
Is the purpose of putting  .conplicity.overrides file at the root of the volume a way  to bypass having non named volume ?

**Comment by mcanevet** [comment]
I'm not sure to understand the question.
`.conplicity.overrides` allows you to specify for each volume whether to ignore it, ignore verification, set the engine (duplicity or rclone) or the provider (postgresql, mysql, openldap) or set the retention policy

**Comment by mcanevet** [comment]
Closing because lack of activity
