### ISSUE TITLE
Bad URL / target on docker backup

### ISSUE THREAD

**Issue by PCatinean** [camptocamp/conplicity#123]
When executing the docker backup command as shown in README the following occurs:

```INFO[0000] Starting volume backup                        backup_dir="/var/lib/docker/volumes/filestore/_data/" full_if_older_than=15D mount="filestore:/var/lib/docker/volumes/filestore/_data:ro" name="filestore" target="/844bd54ddf17/filestore"
INFO[0010] retrying...
INFO[0016] retrying...
ERRO[0019] Failed to backup volume filestore: failed to backup volume: failed to retrieve last backup info: after 3 attempts, last error: failed to retrieve full output from collection-status after 3 attempts

DEBU[0007]  Bad URL '/38f4b4ac2753/filestore'.
 Examples of URL strings are "scp://user@host.net:1234/path" and
 "file:///usr/local".  See the man page for more information.
```
The command from README has been copy pasted with url key and secret key changed

It seems that for some reason the target is not being propagated from the environment

**Comment by mcanevet** [comment]
@PCatinean could you provide us the whole command you run?

**Comment by PCatinean** [comment]
@mcanevet i'm sorry for the noise, I deleted all volumes copy pasted the string again and it started working out of the blue. I only then noticed an environment variable was misnamed :(
