### ISSUE TITLE
MySQL volume provider is not detected

### ISSUE THREAD

**Issue by MorbZ** [camptocamp/conplicity#125]
As you can see from the log file the MySQL provider isn't detected:
```
conplicity_1  | time="2017-07-30T13:43:12Z" level=info msg="Detecting provider" volume="wordpress_mysql" 
conplicity_1  | time="2017-07-30T13:43:12Z" level=info msg="Found data provider" provider=Default volume="wordpress_mysql" 
conplicity_1  | time="2017-07-30T13:43:12Z" level=info msg="No prepare command to execute in container" container=XXX volume="wordpress_mysql" 
conplicity_1  | time="2017-07-30T13:43:12Z" level=info msg="Found backup engine" engine=Duplicity volume="wordpress_mysql" 
```
Using image: camptocamp/conplicity:0.26.3
And mysql:5.7 image with docker-compose: 
```
volumes:
      - mysql:/var/lib/mysql
```

A "mysql" directory is present in the root of the volume so it should be detected but it isn't.

EDIT: It works fine when using the Go binary instead of using the Docker image

**Comment by raphink** [comment]
Did you expose `/var/lib/docker/volumes` to the conplicity container?

```yaml
   volumes:
    - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
```

**Comment by MorbZ** [comment]
I just ran the Docker command from the example in the readme:
```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock:ro  --rm -ti \
   -e CONPLICITY_TARGET_URL=s3+http://s3-eu-west-1.amazonaws.com/<my_bucket>/<my_dir> \
   -e AWS_ACCESS_KEY_ID=<my_key_id> \
   -e AWS_SECRET_ACCESS_KEY=<my_secret_key> \
     camptocamp/conplicity
```
And it recognizes all volumes and the files are backed up correctly. So it seems not neccessary to mount the Docker volumes directory. But just the raw MySQL files are backup up, no dumps are created.

**Comment by raphink** [comment]
Mounting the Docker volumes directory is not necessary for volumes to be backed up, but it is necessary for detecting which data provider should be used, so if it's not mounted, only the default provider will be used.

The reason is that Conplicity looks for specific files in the volume to determine which provider to use. In order to do this, it needs to be able to access the content of the volume.

**Comment by MorbZ** [comment]
I see, thanks.

Maybe you should add that to the readme as it isn't straight forward to figure out why the provider isn't detected and everything else works.

**Comment by raphink** [comment]
Yes indeed, that would be a good idea.

**Comment by raphink** [comment]
@MorbZ yes, all volumes are listed and backed up, using the default provider. Creating dumps though requires to mount the volumes directory.

I've added a note on this in https://github.com/camptocamp/conplicity/commit/c14430376c353b8703c67604fef03e688b092861
