### ISSUE TITLE
flex-volume support (for rancher >1.6.15 / k8s)

### ISSUE THREAD

**Issue by blaggacao** [camptocamp/conplicity#150]
haven't looked deeper but as it says "named volume" in the docs I might smell a problem here..

**Comment by raphink** [comment]
#139 should fix that in a proper way

**Comment by blaggacao** [comment]
Or https://github.com/camptocamp/conplicity/pull/149?

**Comment by cryptobioz** [comment]
The Kubernetes orchestrator (#149) backups all PVC, so, the volume type is transparent.

**Comment by mcanevet** [comment]
Duplicate of #139 and #140
